#!/usr/bin/expect -f

# get arguments
set private_key_loc [lrange $argv 0 0]
set passphrase [lrange $argv 1 1]

# spawn ssh-add process
spawn ssh-add $private_key_loc

# set timeout for expected input
set timeout 5

# look for input with *passphrase*
expect {
	"*passphrase*"	{send -- "$passphrase\r"}
	timeout			exit
}

# all done
expect eof
