#######################################################################
#
#  Makefile for MW sources
#
#######################################################################

# Turn off default suffixes
.SUFFIXES:
.SUFFIXES: .C .o

# This stuff will be changed when switching to autoconf
CXX = g++
CXXFLAGS = -g


INCLUDES = -I./ -I../ -I./RMComm 
CPPFLAGS = $(INCLUDES)

# Define some macros
MWMASTERSRC = MWDriver.C \
	MWTask.C \
	MWWorkerID.C \
	MWStats.C \
	MWprintf.C

MWMASTEROBJ = $(MWMASTERSRC:.C=.o)

MWWORKERSRC = MWWorker.C \
	MWTask.C \
	MWprintf.C \
	MWWorkerID.C

MWWORKEROBJ = $(MWWORKERSRC:.C=.o)


#
#

# Now the targets
all : mw mwfile mwcondorpvm


mw : $(MWMASTEROBJ) $(MWWORKEROBJ)
	ar cr libMW.a $(MWMASTEROBJ) $(MWWORKEROBJ); ranlib libMW.a

mwfile: 
	cd ./RMComm/MW-File; make all; cd ../..

mwcondorpvm:
	cd ./RMComm/MW-CondorPVM; make all; cd ../..

clean:
	rm -f $(MWMASTEROBJ) $(MWWORKEROBJ)
	cd ./RMComm/MW-File; make clean; cd ../..

# default rule
.C.o:
	${CXX} -c ${CPPFLAGS} ${CXXFLAGS} $<


