#! /usr/bin/perl -w
use strict;
use Config;

my(@signal) = split(/ /, $Config{sig_name});

foreach my $pid (@ARGV) {
	open(my $fh, '<', "/proc/$pid/status")
		or die "Unable to open(</proc/$pid/status): $!";
	my(@body) = <$fh>;
	close $fh;
	my($sigign) = grep(/^SigIgn:/, @body);
	my($mask) = ($sigign =~ /SigIgn:\s*([0-9A-Fa-f]*)/);
	my $blob = pack('H*', $mask);
	my $bitstring = unpack('B*', $blob);
	my(@bits) = split //, $bitstring;
	my $sig = 1;
	for(my $i = $#bits; $i >= 0; $i--, $sig++) {
		if($bits[$i]) { print "$signal[$sig] "; }
	}
	print "\n";
}


