#######################################################################
#
#  Makefile for Condor-PVM based RMComm 
#
#######################################################################

# Turn off default suffixes
.SUFFIXES:
.SUFFIXES: .C .o


CXX= g++
CXXFLAGS = -g
PVM_ROOT = /p/condor/workspaces/pvm/pvm3.4.2

MASTERSRC = ../MWRMComm.C \
	MWCondorPvmRC.C

MASTEROBJ = MWRMComm.o\
	MWCondorPvmRCM.o

WORKERSRC = ../MWRMComm.C \
	MWCondorPvmRC.C

WORKEROBJ = MWRMComm.o\
	MWCondorPvmRCW.o

#
# Put everything together
#

INCLS=	-I../ -I../.. -I$(PVM_ROOT)/include

all: mwcondorpvmmaster mwcondorpvmworker

mwcondorpvmmaster: $(MASTEROBJ)
	ar cr libMWcondorpvmmaster.a $(MASTEROBJ)
	ranlib libMWcondorpvmmaster.a

mwcondorpvmworker: $(WORKEROBJ)
	ar cr libMWcondorpvmworker.a $(WORKEROBJ)
	ranlib libMWcondorpvmworker.a

clean:
	rm -f $(MASTEROBJ) $(WORKEROBJ)

MWCondorPvmRCM.o: MWCondorPvmRC.C MWCondorPvmRC.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(INCLS) -DPVM_MASTER  -c MWCondorPvmRC.C -o MWCondorPvmRCM.o

MWCondorPvmRCW.o: MWCondorPvmRC.C MWCondorPvmRC.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(INCLS) -c MWCondorPvmRC.C -o MWCondorPvmRCW.o

MWRMComm.o: ../MWRMComm.C ../MWRMComm.h
	${CXX} ${CPPFLAGS} ${CXXFLAGS} $(INCLS) -c ../MWRMComm.C

.C.o:
	${CXX} -c ${CPPFLAGS} ${CXXFLAGS} $(INCLS) $<

