#! /usr/bin/perl
opendir D, '.' or die "$!";
while($_ = readdir D) {
	next if system("file $_ | grep perl > /dev/null");
	my $w = system("/bin/grep 'use warning' $_ > /dev/null");
	my $s = system("/bin/grep 'use strict' $_ > /dev/null");
	if($w or $s) {
		print "$_: ";
		print "use warnings; " if $w;
		print "use strict; " if $s;
		print "\n";
	}
}
