#######################################################################
#
#  Makefile for the fibonacci example application
#
#######################################################################

CC= /s/ogcc/bin/g++

CFLAGS = -g -Wall
CDEFINES =  -DINDEPENDENT

PURIFY = purify -collector=/s/ogcc/bin/g++

# Just master objects
MWOBJS = ../../MWDriver.o \
	../../MWTask.o \
	../../MWWorkerID.o \
	../../MWStats.o \
	../../MWprintf.o \
	../../MWMasterMain.o \
	../../MWWorker.o \
	../../CommRM/MW-Independent/MWIndRC.o


MASTER_NAME     = master-fib_ind

DOC_TARGET_DIR  = ./html/

APP_HEADERS     = Driver-fib.h Task-fib.h Worker-fib.h
MASTERSOURCES   = Driver-fib.C Task-fib.C Worker-fib.C

MASTEROBJS      = $(MASTERSOURCES:C=o)

DOCDIR          = /unsup/doc++/bin
DOCOPTIONS      = -p
DOCS            = $(APP_HEADERS:.h=.doc)


DEPGEN=	makedepend
# (Need this so that makedepend doesn't complain)
CCINCLS= -I/s/gcc/include/g++ -I/s/gcc/@sys/i386-pc-solaris2.6/include
#CCINCLS= -I/s/gcc/include/g++ -I/s/gcc/@sys/sparc-sun-solaris2.6/include

#
# Put everything together
#

INCLS=	-I./ -I../../ -I../../CommRM/ -I../../CommRM/MW-Independent/
LIBS=	
DEFINES= $(CDEFINES)

all: master 

master: $(MWOBJS) $(MASTEROBJS)
	$(CC) $(CFLAGS) -o $(MASTER_NAME) \
		$(MWOBJS) $(MASTEROBJS) $(LIBS) 
	@echo " *** Master Fib. created ***"

depend:
	$(DEPGEN) $(INCLS) $(CCINCLS) $(DEFINES) $(ALLSOURCES)
	@echo " *** Done making depend"

clean:
	rm -f $(MASTEROBJS) core
	@echo " *** You're clean now"

reallyclean: clean
	rm -f $(MASTER_NAME) $(WORKER_NAME) $(DOCS) out_* work.log
	rm -f $(MASTEROBJS) $(MWOBJS) core
	@echo " *** You're really clean now."

myclean:
	/bin/rm ./submit_files/* ./worker_input/* ./worker_output/* core*

doc: $(DOCS)
	$(DOCDIR)/doc++ -d $(DOC_TARGET_DIR) \
		$(DOCOPTIONS) $(DOCS); \
	rm -f $(DOCS)
	@echo " *** Made doc++"

######################################################################

.SUFFIXES: .o .C .doc

#.C.o:
#	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o $(<:C=o) $<

../../MWMasterMain.o: ../../MWMasterMain.C ../../MWDriver.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWMasterMain.o ../../MWMasterMain.C

../../MWDriver.o: ../../MWDriver.C ../../MWDriver.h ../../CommRM/MWRMComm.h ../../MWTask.h ../../MWWorker.h ../../MWWorkerID.h ../../MW.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWDriver.o ../../MWDriver.C

../../MWWorker.o: ../../MWWorker.C ../../MWWorker.h ../../CommRM/MWRMComm.h ../../MWTask.h ../../MW.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWWorker.o ../../MWWorker.C

../../MWTask.o: ../../MWTask.C ../../MWTask.h ../../CommRM/MWRMComm.h ../../MW.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWTask.o ../../MWTask.C

../../MWStats.o: ../../MWStats.C ../../MWStats.h ../../MWWorkerID.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWStats.o ../../MWStats.C

../../MWWorkerID.o: ../../MWWorkerID.C ../../MWWorkerID.h ../../MWTask.h ../../MW.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWWorkerID.o ../../MWWorkerID.C

../../MWprintf.o: ../../MWprintf.C ../../MWprintf.h ../../MW.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../MWprintf.o ../../MWprintf.C

../../CommRM/MW-Independent/MWIndRC.o: ../../CommRM/MW-Independent/MWIndRC.h ../../CommRM/MWRMComm.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o ../../CommRM/MW-Independent/MWIndRC.o ../../CommRM/MW-Independent/MWIndRC.C

Driver-fib.o: Driver-fib.C Driver-fib.h ../../MWWorker.h ../../MWTask.h ../../MW.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o Driver-fib.o Driver-fib.C

Task-fib.o: Task-fib.C Task-fib.h ../../MW.h ../../MWTask.h
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o Task-fib.o Task-fib.C

Worker-fib.o: Worker-fib.C Worker-fib.h Task-fib.h 
	$(CC) $(CFLAGS) $(DEFINES) $(INCLS) -c -o Worker-fib.o Worker-fib.C

.h.doc:
	$(DOCDIR)/docify $< > $(<:h=doc)
# DO NOT DELETE
