#######################################################################
#
#  Makefile for the fibonacci example application
#
#######################################################################

# Turn off default suffixes
.SUFFIXES:
.SUFFIXES: .C .o

# The user puts this or configure?
MWDIR=../..
CONDOR_DIR = /unsup/condor

CONDORPVM_DIR = /p/condor/workspaces/pvm/pvm3.4.2
PVM_ARCH = LINUX
SOCKET_LIB = #-lsocket -lnsl

CXX = g++
CXXFLAGS = -g
INCL = -I$(MWDIR)/src -I$(MWDIR)/src/RMComm


# Now some macros
MASTERSRC   = Driver-fib.C Task-fib.C MasterMain-fib.C
WORKERSRC   = Worker-fib.C Task-fib.C WorkerMain-fib.C

MASTEROBJ      = $(MASTERSRC:.C=.o)
WORKEROBJ      = $(WORKERSRC:.C=.o)

# Now the targets

all:	file-based condorpvm-based

file-based: filemaster fileworker

condorpvm-based: condorpvmmaster condorpvmworker

filemaster: $(MASTEROBJ)
	$(CXX) -o masterfib-file $(CXXFLAGS) $(LDFLAGS) $(MASTEROBJ)\
	-L$(MWDIR)/lib   -lMWfilemaster -lMW -L$(CONDOR_DIR)/lib -lcondorapi

fileworker: $(WORKEROBJ)
	$(CXX) -o workerfib-file $(CXXFLAGS) $(LDFLAGS) $(WORKEROBJ) \
		-L$(MWDIR)/lib -lMWfileworker  -lMW  -L$(CONDOR_DIR)/lib -lcondorapi

condorpvmmaster: $(MASTEROBJ)
	$(CXX) -o masterfib-condorpvm $(MASTEROBJ) \
	-L$(MWDIR)/lib   -lMWcondorpvmmaster -lMW \
	-L$(CONDORPVM_DIR)/lib/$(PVM_ARCH) -lpvm3 $(SOCKET_LIB)

condorpvmworker: $(WORKEROBJ)
	$(CXX) -o workerfib-condorpvm $(WORKEROBJ) \
	-L$(MWDIR)/lib   -lMWcondorpvmworker -lMW \
	-L$(CONDORPVM_DIR)/lib/$(PVM_ARCH) -lpvm3 $(SOCKET_LIB)

clean:
	rm -f $(MASTEROBJ) $(WORKEROBJ)


# default rule
.C.o:
	${CXX} -c ${CPPFLAGS} ${CXXFLAGS} $(INCL) $<
